config/routes.rb
Rails.application.routes.draw do
  
  

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'

  resources :users

end

app/models/car.rb
class Car < ActiveRecord::Base

	has_many :ratings

	validates :price, numericality: {greather_than: 0} 
	validates :stock, numericality: true

	mount_uploader :photo, ImageUploader

	def total_value
		price * stock
	end

	def self.most_expensive
		order(price: :desc).first
	end

	def average_rating
  		ratings.sum(:score) / ratings.size unless ratings.empty?
	end
  

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :car

end

app/models/user.rb
class User < ActiveRecord::Base

	before_save { self.email = email.downcase }
	validates :name, presence: true, length: {maximum: 50}
	validates :password, length: { minimum: 6 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false}

    has_secure_password
	 
end

app/controllers/application_controller.rb
# @class ApplicationController
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/cars_controller.rb
# @class CarsController
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
    @most_expe = Car.most_expensive
   
   

  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:color, :hp, :model, :price, :stock, :photo)
    end
end

app/controllers/mailer_controller.rb
class MailerController < ApplicationController

	def send_email
	UserMailer.welcome_email("example@mail.com").deliver_now
	redirect_to root_path
	end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def create
    @rating = Rating.new
    @rating.score = params[:score]
    @car = Car.find(params[:car_id])
    @car.ratings << @rating
    @car.save
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	#Return the full title
	def full_title(page_title = '')
		base_title = "Ruby on rails application"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_mailer_helper.rb
module UserMailerHelper
end

app/helpers/users_helper.rb
module UsersHelper

	#Gravatar
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
	    image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
<div class="col-xs-4 col-md-4">
  <div class="form-group">
    <%= f.label :color%><br>
    <%= f.text_field :color, class: "form-control" %>
  </div>
  <div class="control-group">
    <%= f.label :hp %><br>
    <%= f.number_field :hp, class: "form-control" %>
  </div>
  <div class="control-group">
    <%= f.label :model %><br>
    <%= f.text_field :model, class: "form-control"%>
  </div>
  <div class="control-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control"%>
  </div>
  <div class="control-group">
    <%= f.label :stock %><br>
    <%= f.text_field :stock, class: "form-control"%>
  </div>
  <div class="control-group">
    <%= f.file_field :photo %><br>
  </div>



  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
  </div>

<% end %>

app/views/cars/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">SoftVision Lab Application</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Cars <span class="sr-only">(current)</span></a></li>
        <li><a href="#">About</a></li>
        <li><%= link_to "Send Mail", mailer_path, method: :post %> </li>

      </ul>
    </li>
  </ul>

  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
<body>
  <div class="row">
    <div class=".col-xs-6 .col-md-4">
      <p id="notice"><%= notice %></p>
      <div class="cars_title">
        <h1>Listing Cars</h1>
      </div>
      <div class="cars_list">
        <table class="table">
          <thead>
            <tr>
               <th colspan="1"></th>
              <th>Color</th>
              <th>Hp</th>
              <th>Model</th>
              <th>Price</th>
              <th>Stock</th>
       
              <th>Average Rating </th>
              <th> Your Rating </th>
              <th colspan="1"></th>
              <th> Actions </th>

            </tr>
          </thead>

          <tbody>
            <% @cars.each do |car| %>
            <tr>
             <td class="col-md-1"> <%= image_tag(car.photo_url(:thumb)) if car.photo? %></td> 
              <td class="col-md-1"><%= car.color %></td>
              <td class="col-md-1"><%= car.hp %></td>
              <td class="col-md-1"><%= car.model %></td>
              <td class="col-md-1"><%= car.price %></td>
              <td class="col-md-1"><%= car.stock %></td>
             
              <td>
               <!--  <p>Averate rating</p> -->
               <div class="star" data-average-rating = "<%= car.average_rating %>"></div>
             </td>
             <td>
              <!--   <p>Your rating</p> -->
              <div class="user_star" data-car-id = "<%= car.id %>"></div>
            </td>
            <td class="col-md-1"><%= link_to 'Show', car, :class => "" %></td>
            <td class="col-md-1"><%= link_to 'Edit', edit_car_path(car), :class => "" %></td>
            <td class="col-md-1"><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' }, :class => "" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <p>Most expensive car:</p>
      <%= @most_expe.model%>
      <br>
      <br>
      <%= link_to 'New Car', new_car_path ,:class => "btn btn-default"%>
    </div>
  </div>
</div>
<body>

app/views/cars/show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">SoftVision Lab Application</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/cars">Cars <span class="sr-only">(current)</span></a></li>
        <li><a href="#">About</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @car.hp %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car.price %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @car.stock %>
</p>
<p>
  <strong>Image:</strong>
  <%= image_tag(@car.photo_url) if @car.photo? %>
</p>


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Hello! Have a nice day!
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  		<nav class="navbar navbar-default">
  			<div class="container-fluid">
  				<!-- Brand and toggle get grouped for better mobile display -->
  				<div class="navbar-header">
  					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
  						<span class="sr-only">Toggle navigation</span>
  						<span class="icon-bar"></span>
  						<span class="icon-bar"></span>
  						<span class="icon-bar"></span>
  					</button>
            <a> <%= link_to "TEXRIFYME", root_path,class:"navbar-brand" %></a>
  				</div>

  				<!-- Collect the nav links, forms, and other content for toggling -->
  				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  					<ul class="nav navbar-nav">
  						<li><%= link_to "Home", root_path %><span class="sr-only">(current)</span></a></li>
  						<li><%= link_to "About", about_path %></li>
              <li><%= link_to "Help", help_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
  						<li><%= link_to "Log in" %></li>
  					</ul>
  				</div><!-- /.navbar-collapse -->
  			</div><!-- /.container-fluid -->
  		</nav>
  	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
      <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
	 <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>


</body>
</html>

app/views/ratings/update.js.erb
$('#star').raty({
  readOnly: true,
  score: <%= @car.average_rating %>,
  path: '/assets'
});

$('#user_star').raty({
  score: <%= @rating.score %>,
  path: '/assets',
  click: function(score, evt) {
    $.ajax({
      url: '/ratings/' + <%= @rating.id %>,
      type: 'PATCH',
      data: { score: score }
    }).done(function (data){});
  }
});

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>This is the about page</h1>
<p>Content will be added soon</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact us !
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>This is the help page</h1>
<p>Content will be added soon</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
<h1>Welcome</h1>

<h2>This is the home page</h2>
<br>
<p>Content will be added soon</p>

 <%= link_to "Sign up now!", 'signup', class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>